### ISSUE TITLE
GitHub OAuth asks for read/write access on accounts

### ISSUE THREAD

**Issue by cassidyjames** [elementary/builds#24]
As I understand it, this is a limitation of the GitHub API? But I'm opening an issue here since it's something folks have been asking us about—and in case there is anything we could do differently now or in the future to reduce the requested scope.

**Comment by btkostner** [comment]
I just looked, there are no actual permissions we set for oauth apps. Everything is just hard set by GitHub itself. So, unless we move this to a GitHub app (which we shouldn't), this can not be changed.

**Comment by btkostner** [comment]
errr, sorry, I had this confused with the houston integration. PR incoming.

**Comment by gargoyle** [comment]
I did a bit of testing on this earlier.

It looks like a GitHub bug (or a poorly implemented feature). I see no reason to require write access to a users profile in order to only read their list of subscriptions. So I have opened a support request and will update here if/when I get a response.

If you remove the "tier" request from the GraphQL query, then you can see a users subscriptions without requesting any scope at all. But you are then limited to only knowing they sponsor the project and not at what tier.

![image](https://user-images.githubusercontent.com/437990/89956618-67b86c00-dc2d-11ea-89bb-179cf31cbc28.png)

**Comment by btkostner** [comment]
@gargoyle ahhh. I would not be surprised. I have encountered a couple of similar errors in the GitHub API. Thank you for taking a look at this!

**Comment by gargoyle** [comment]
I've just had an email from GH.

> Hi Paul,
> This issue was recently escalated to our Engineering team and it's been resolved!
> You should be able to use the ['read:user'] scope without getting errors for the monthlyPriceInCents field.

I'm not in a position to re-do my tests today, but might have time early next week if needed. But it might be quicker for you to retry the change in PR 25. (https://github.com/elementary/builds/pull/25)

**Comment by btkostner** [comment]
Awesome. Thank you for doing a bunch of the leg work and going above and beyond to mail GitHub! That's really awesome!

I should be able to test this out pretty easily. Give me a few days and I should be able to update that PR.

**Comment by alexellis** [comment]
Really pleased to see this - it was affecting users of my [Treasure Trove](https://faasd.exit.openfaas.pro/function/trove/login/?r=) sponsors portal too.
